In [1]:
x = 3
print(x)

3


In [2]:
type(x)

int

In [3]:
print("hello world")

hello world


In [5]:
print(x+5)
print(x+5*10) # bedmas rule

8
53


In [6]:
print(x -2*5/10)

2.0


In [8]:
x = 10
x+=5
print(x)

15


In [10]:
a,b=True,False
print(a)
print(b)

True
False


In [11]:
print(type(a))

<class 'bool'>


In [12]:
a =10
print(type(a))

<class 'int'>


In [13]:
a,b=True,False
print(a and b) #and operation

False


In [14]:
print( a or b) #or operation

True


In [15]:
print( a!=b) #xor opeartion

True


In [16]:
d = "wild"
f="sjbit"
print(d,len(f))

wild 5


In [19]:
d = "hello"
w= " world how are you"

s = d + w
print(s)

hello world how are you


In [20]:
d = "hello"
w= " world how are you"
print(d,f,sep="\n")# separtion of the two words using this command

hello
sjbit


In [21]:
#string opeartion
b = "neeraj"
print(len(b))

6


In [47]:
b = "neeraj"
print(b.capitalize()) # using the capatialize ficntion
print(b.casefold())
print(b.upper())
print(b.center(10))
print(b.replace("ne","(N)(e)"))


Neeraj
neeraj
NEERAJ
  neeraj  
(N)(e)eraj


In [46]:
#lists
c = [10,5,6]
print(c[0])

10


In [49]:
c.append("max")
print(c)

[10, 5, 6, 'max', 'max']


In [50]:
#loops
n = "blaz"
for i in n:
    print(i)

b
l
a
z


In [51]:
n = "blaz"
for i in n:
    print(n)

blaz
blaz
blaz
blaz


In [53]:
n = "mad max"
for i in n:
    print(n)

mad max
mad max
mad max
mad max
mad max
mad max
mad max


In [54]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [55]:
#loops
car = ["volswagen","bucati","astonmatrin"]
for i in car:
    print(i)

volswagen
bucati
astonmatrin


In [59]:
#while statement
i = 1
while i<=10:
    print(i)
    i = i+1
    if i == 4:
        break
        print(i)



1
2
3


In [70]:
i = 1
while i<=10:
    
    i = i+1
    if i == 4:
        continue
    print(i)
        
       
        

2
3
5
6
7
8
9
10
11


In [71]:
#tuples and dictanaries and fuctions
sag=(4,8,9)
type(sag) # tuples are immutable



tuple

In [73]:
print("c cor:",sag[0])
print("d cor:",sag[1])
print("e cor:",sag[2])

c cor: 4
d cor: 8
e cor: 9


In [74]:
elements={"ronaldo":1,"messi":2}
type(elements)

dict

In [75]:
print("ronaldo" in elements)

True


In [76]:
!jt -l


Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


In [ ]:
!jt -t chesterish


In [78]:
print("hello world")

hello world


In [ ]:
!jt -t grade3

In [82]:
!jt -t oceans16

In [83]:
!jt -t onedork

In [84]:
!jt -t solarizedd


In [86]:
 !jt -r

Reset css and font defaults in:
C:\Users\USER\.jupyter\custom &
C:\Users\USER\AppData\Roaming\jupyter\nbextensions


# numpy and pandas


In [2]:
import numpy as np
x = np.array([1,2,3,4,5,6])
print(type(x))


<class 'numpy.ndarray'>


In [3]:
x =np.array([1,2,3,"hello"])
x

array(['1', '2', '3', 'hello'], dtype='<U11')

In [4]:
a=[1,2,3,4,[2,5]]
a

[1, 2, 3, 4, [2, 5]]

In [9]:
x=np.array([[1,2,3],[4,5,6],[7,8,9] ])
x.shape

(3, 3)

In [10]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
x=np.zeros((3,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
x=np.diag([10,20,30])
x

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [19]:
x=np.eye(3)#idintity matrix
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
x=np.eye(3,dtype=np.int64)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [21]:
x=np.arange(0,25)

In [22]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
x=np.linspace(0,25,10)
x

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [24]:
x=np.reshape(x,(5,2))

In [25]:
x

array([[ 0.        ,  2.77777778],
       [ 5.55555556,  8.33333333],
       [11.11111111, 13.88888889],
       [16.66666667, 19.44444444],
       [22.22222222, 25.        ]])

In [26]:
x=np.random.random()
x

0.6611531921815741

In [28]:
x=np.random.randint(0,60,size=(3,2))# 3 rows and two coloums

In [29]:
x

array([[29,  8],
       [52, 28],
       [33, 32]])

In [ ]:
# to fetch the value from the matrix

In [31]:
x[0,0]


29

In [32]:
x[1,1]

28

In [33]:
x=np.array([1,2,3,4,5])
print(x.max())

5


In [34]:
x.mean()


3.0

In [35]:
y=[1,2,3,4]
y*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [36]:
x=np.random.randint(0,60,size=(3,2))
x

array([[22, 57],
       [50, 19],
       [56, 22]])

In [37]:
x*2 #matrix hets multiplied by 2


array([[ 44, 114],
       [100,  38],
       [112,  44]])

# pandas

In [6]:
import pandas as pd


In [48]:
df_students=pd.read_rsv("grades,csv")


AttributeError: module 'pandas' has no attribute 'read_rsv'

In [49]:
df_students=pd.read_rsv

AttributeError: module 'pandas' has no attribute 'read_rsv'

In [50]:
df_students.isnull().sum()

NameError: name 'df_students' is not defined

In [5]:
x=pd.series([1,2,3,4,5])

AttributeError: module 'pandas' has no attribute 'series'

In [55]:
x.max()

57

In [7]:
import pandas as pd
x=pd.series([1,2,3,4,5])

AttributeError: module 'pandas' has no attribute 'series'

# data visulaization

In [10]:
import matplotlib.pyplot as plt
dir(plt)

['Annotation',
 'Arrow',
 'Artist',
 'AutoLocator',
 'Axes',
 'Button',
 'Circle',
 'Figure',
 'FigureCanvasBase',
 'FixedFormatter',
 'FixedLocator',
 'FormatStrFormatter',
 'Formatter',
 'FuncFormatter',
 'GridSpec',
 'IndexLocator',
 'Line2D',
 'LinearLocator',
 'Locator',
 'LogFormatter',
 'LogFormatterExponent',
 'LogFormatterMathtext',
 'LogLocator',
 'MaxNLocator',
 'MouseButton',
 'MultipleLocator',
 'Normalize',
 'NullFormatter',
 'NullLocator',
 'Number',
 'PolarAxes',
 'Polygon',
 'Rectangle',
 'ScalarFormatter',
 'Slider',
 'Subplot',
 'SubplotTool',
 'Text',
 'TickHelper',
 'Widget',
 '_INSTALL_FIG_OBSERVER',
 '_IP_REGISTERED',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_auto_draw_if_interactive',
 '_backend_mod',
 '_code_objs',
 '_copy_docstring_and_deprecators',
 '_get_required_interactive_framework',
 '_interactive_bk',
 '_log',
 '_pylab_helpers',
 '_setup_pyplot_info_docstrings',
 '_warn_if_gui_ou

In [11]:
help(plt.bar)

Help on function bar in module matplotlib.pyplot:

bar(x, height, width=0.8, bottom=None, *, align='center', data=None, **kwargs)
    Make a bar plot.
    
    The bars are positioned at *x* with the given *align*\ment. Their
    dimensions are given by *height* and *width*. The vertical baseline
    is *bottom* (default 0).
    
    Many parameters can take either a single value applying to all bars
    or a sequence of values, one for each bar.
    
    Parameters
    ----------
    x : float or array-like
        The x coordinates of the bars. See also *align* for the
        alignment of the bars to the coordinates.
    
    height : float or array-like
        The height(s) of the bars.
    
    width : float or array-like, default: 0.8
        The width(s) of the bars.
    
    bottom : float or array-like, default: 0
        The y coordinate(s) of the bars bases.
    
    align : {'center', 'edge'}, default: 'center'
        Alignment of the bars to the *x* coordinates:
    
   

In [12]:
plt.bar(x=df_students.names,height=df_students.grade,color="orange")
plt.xticks(rotation=90)
plt.show

NameError: name 'df_students' is not defined

In [13]:
help(plt.subplot)

Help on function subplot in module matplotlib.pyplot:

subplot(*args, **kwargs)
    Add a subplot to the current figure.
    
    Wrapper of `.Figure.add_subplot` with a difference in behavior
    explained in the notes section.
    
    Call signatures::
    
       subplot(nrows, ncols, index, **kwargs)
       subplot(pos, **kwargs)
       subplot(**kwargs)
       subplot(ax)
    
    Parameters
    ----------
    *args : int, (int, int, *index*), or `.SubplotSpec`, default: (1, 1, 1)
        The position of the subplot described by one of
    
        - Three integers (*nrows*, *ncols*, *index*). The subplot will take the
          *index* position on a grid with *nrows* rows and *ncols* columns.
          *index* starts at 1 in the upper left corner and increases to the
          right. *index* can also be a two-tuple specifying the (*first*,
          *last*) indices (1-based, and including *last*) of the subplot, e.g.,
          ``fig.add_subplot(3, 1, (1, 2))`` makes a subplot t