# to stack two array top of each other 

In [2]:
import numpy as np


In [4]:
a = np.random.randint(10,size=(3,3))
print(a)

[[1 7 5]
 [9 5 8]
 [1 5 6]]


In [6]:
b=np.random.randint(20,size=(3,3))
print(b)

[[17  0 14]
 [ 2 11  2]
 [17 17 11]]


# to stack vertically

In [7]:
np.vstack((a,b))

array([[ 1,  7,  5],
       [ 9,  5,  8],
       [ 1,  5,  6],
       [17,  0, 14],
       [ 2, 11,  2],
       [17, 17, 11]])

# to stack horizontally

In [8]:
np.hstack((a,b))

array([[ 1,  7,  5, 17,  0, 14],
       [ 9,  5,  8,  2, 11,  2],
       [ 1,  5,  6, 17, 17, 11]])

# we can split the given array using the syntax :np.hsplit()

In [10]:
#initialize an random array
p = np.random.randint(10,size=(5,5))
print(p)

[[0 4 7 3 6]
 [6 7 6 7 1]
 [2 6 4 3 0]
 [5 2 9 0 2]
 [2 2 2 6 9]]


In [13]:
np.hsplit(p,1)

[array([[0, 4, 7, 3, 6],
        [6, 7, 6, 7, 1],
        [2, 6, 4, 3, 0],
        [5, 2, 9, 0, 2],
        [2, 2, 2, 6, 9]])]

In [14]:
p = np.random.randint(10,size=(2,15))
print(p)

[[3 9 9 4 5 3 3 3 9 7 5 5 2 9 6]
 [6 5 7 6 0 9 3 7 7 5 9 4 9 0 7]]


In [15]:
np.hsplit(p,3)# we can split the array into three different sections

[array([[3, 9, 9, 4, 5],
        [6, 5, 7, 6, 0]]),
 array([[3, 3, 3, 9, 7],
        [9, 3, 7, 7, 5]]),
 array([[5, 5, 2, 9, 6],
        [9, 4, 9, 0, 7]])]

In [16]:
np.vsplit(p,2)#we can split the array horizontally

[array([[3, 9, 9, 4, 5, 3, 3, 3, 9, 7, 5, 5, 2, 9, 6]]),
 array([[6, 5, 7, 6, 0, 9, 3, 7, 7, 5, 9, 4, 9, 0, 7]])]

# indexing and slicing the three dimensional array

In [18]:
q = np.random.randint(42,size=(6,7))
print(q)

[[ 1 21  7 27 16  2 26]
 [ 0 34 37 16 15 26 16]
 [ 9  2 14 36 41 15 27]
 [18 36  8  1 33  6 20]
 [16 26 12 15 27  2  3]
 [30 30 30 10 36 33 26]]


In [21]:
q = np.arange(42).reshape(6,7)
print(q)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [22]:
q[:,1:2]

array([[ 1],
       [ 8],
       [15],
       [22],
       [29],
       [36]])

In [23]:
#to extract the element 1,8,15
q[0:3,1]

array([ 1,  8, 15])

In [ ]:
#to extract the elements from the midlle of the matrix for example (7,8,14,15) hint:indexing is sampe as slicing in noraml python

In [24]:
q[1:3,0:2]

array([[ 7,  8],
       [14, 15]])

# to extract the element by leaving the coloums and rows

In [25]:
q = np.arange(42).reshape(6,7)
print(q)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [26]:
q[0::2,:] #herer we printed only the odd rowss

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [27]:
# in the sameway if we want to print the coloums 
q[:,0::2]


array([[ 0,  2,  4,  6],
       [ 7,  9, 11, 13],
       [14, 16, 18, 20],
       [21, 23, 25, 27],
       [28, 30, 32, 34],
       [35, 37, 39, 41]])