In [1]:
import numpy as np
a=c =np.array([1,2,3,4,5,6])
print(c)

[1 2 3 4 5 6]


In [2]:
c.ndim

1

In [3]:
a =np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(a)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
b=np.array([[1,2,3,4,5],[7,9,4,2,6]])

In [5]:
b

array([[1, 2, 3, 4, 5],
       [7, 9, 4, 2, 6]])

In [6]:
# to get the dimension
b.ndim

2

In [7]:
a.ndim

2

In [8]:
a.shape # this indiactes three rows and two coloums

(2, 3)

In [9]:
d=np.array([[1,2,3],[4,5,6],[6,7,8]],dtype="int32")
print(d)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [10]:
d.ndim

2

In [11]:
d.shape #three rows ans three coloums

(3, 3)

In [12]:
d.dtype

dtype('int32')

In [13]:
d.itemsize


4

In [14]:
d=np.array([[1,2,3,10],[4,5,6,10],[6,7,8,10]],dtype="int32")
print(d)

[[ 1  2  3 10]
 [ 4  5  6 10]
 [ 6  7  8 10]]


In [15]:
d.itemsize

4

In [16]:
#to get the total size
d.itemsize #itemsize returns the size (in bytes) of each element of a NumPy array.







4

In [17]:
d.shape

(3, 4)

In [18]:
d.size # indicates the total 

12

In [19]:
d.itemsize #itemsize returns the size (in bytes) of each element of a NumPy array.


4

In [20]:
d.nbytes 

48

In [21]:
#to get the total size
a.size*a.itemsize


48

# extracting the elements from the given array

In [22]:
import numpy as np
d=np.array([[1,2,3,4],[5,6,7,8]])
print(d)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
d.ndim

2

In [24]:
d.shape

(2, 4)

In [25]:
d.size


8

In [26]:
d.itemsize

4

In [27]:
#to extract the specific element
d[1,1]

6

In [28]:
d[1,3]

8

# indexing and slicing

In [29]:
h = np.array([[6,7,8],[1,2,3],[9,3,2]])
print(h)

[[6 7 8]
 [1 2 3]
 [9 3 2]]


In [30]:
#to go through all the rows syntax:[:,:]

In [31]:
h[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [32]:
h[:,1:2]

array([[7],
       [2],
       [3]])

In [33]:
h[:,0:1]

array([[6],
       [1],
       [9]])

In [34]:
h[:,0:3]

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [35]:
h[:,2:3]

array([[8],
       [3],
       [2]])

In [36]:
h[:,2:3]

array([[8],
       [3],
       [2]])

# to print the rows 

In [37]:
h[0,:]

array([6, 7, 8])

In [38]:
h[1,:]

array([1, 2, 3])

In [39]:
h[2,:]

array([9, 3, 2])

In [40]:
h[-1,:]

array([9, 3, 2])

In [41]:
h[-2,:]

array([1, 2, 3])

# to print the coloums

In [42]:
h[:,1]

array([7, 2, 3])

In [43]:
h[:,2]

array([8, 3, 2])

In [44]:
h[:,0]

array([6, 1, 9])

In [45]:
h[:,-1]

array([8, 3, 2])

# to flaten the element of array

In [46]:
h.flatten()


array([6, 7, 8, 1, 2, 3, 9, 3, 2])

In [47]:
for i in h.flat:
    print(i)

6
7
8
1
2
3
9
3
2


In [48]:
np.arange(6,12).reshape(3,2)

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [49]:
d[0,:]#extracting the whole row

array([1, 2, 3, 4])

In [50]:
d[:,1]#extracting the whole coloumn

array([2, 6])

In [51]:
d[:,2]

array([3, 7])

In [52]:
#to extract the specified elements with the row
d[0,1:4]

array([2, 3, 4])

In [53]:
d[0,0:4]

array([1, 2, 3, 4])

In [54]:
d[0,0:4:2]

array([1, 3])

In [55]:
r=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(r)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [56]:
r[:,2]

array([3, 9])

In [57]:
r[1,:]

array([ 7,  8,  9, 10, 11, 12])

In [58]:
r[0,2:6]

array([3, 4, 5, 6])

In [59]:
r[0,2:6:2]

array([3, 5])

In [60]:
r[0,1:-3]

array([2, 3])

In [61]:
r[1,1:12]

array([ 8,  9, 10, 11, 12])

In [62]:
r[1,1:12:2]

array([ 8, 10, 12])

In [63]:
r[1,1:-1]

array([ 8,  9, 10, 11])

In [127]:
r

array([[ 1,  2, 15, 15, 15, 15],
       [ 7,  8,  9, 10, 11, 12]])

In [128]:
r=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(r)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [64]:
#to change the element in numpy or to update an element in array
r[1,3] = 11
print(r)


[[ 1  2  3  4  5  6]
 [ 7  8  9 11 11 12]]


In [65]:
r[1,5] = 13
print(r)

[[ 1  2  3  4  5  6]
 [ 7  8  9 11 11 13]]


In [66]:
r[0,:] = 17
print(r)

[[17 17 17 17 17 17]
 [ 7  8  9 11 11 13]]


In [67]:

r=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(r)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [68]:
r[0,2:6]

array([3, 4, 5, 6])

In [69]:
r[0,1:5]

array([2, 3, 4, 5])

In [70]:
r[0,0:3]

array([1, 2, 3])

In [71]:
r[0,2:6] = 15
print(r)

[[ 1  2 15 15 15 15]
 [ 7  8  9 10 11 12]]


# three dimensional array

In [72]:
t = np.array([[[1,2,4],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t)

[[[ 1  2  4]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [73]:
t[0,0,2]

4

In [74]:
t[1,1,2]

12

In [75]:
t[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [76]:
t[:,0,:]

array([[1, 2, 4],
       [7, 8, 9]])

In [77]:
#replacing the the rows and coloums in the set

In [78]:
t[:1,:] = 23
print(t)

[[[23 23 23]
  [23 23 23]]

 [[ 7  8  9]
  [10 11 12]]]


In [79]:
t = np.array([[[1,2,4],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t)

[[[ 1  2  4]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [80]:
t[:,1,1:] = 24
print(t)

[[[ 1  2  4]
  [ 4 24 24]]

 [[ 7  8  9]
  [10 24 24]]]


In [81]:
t[:,0,:] = 25
print(t)

[[[25 25 25]
  [ 4 24 24]]

 [[25 25 25]
  [10 24 24]]]


In [82]:
t = np.array([[[1,2,4],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t)

[[[ 1  2  4]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [83]:
t[:,1,:1] = 23
print(t)

[[[ 1  2  4]
  [23  5  6]]

 [[ 7  8  9]
  [23 11 12]]]


In [84]:
t[:,1,1:] = 23
print(t)

[[[ 1  2  4]
  [23 23 23]]

 [[ 7  8  9]
  [23 23 23]]]


In [85]:
t[:,0,1:] = 24
print(t)

[[[ 1 24 24]
  [23 23 23]]

 [[ 7 24 24]
  [23 23 23]]]


In [86]:
t[:,0,0:] = 24 #remmber this command for cahnging the row elements
print(t)

[[[24 24 24]
  [23 23 23]]

 [[24 24 24]
  [23 23 23]]]


In [87]:
t = np.array([[[1,2,4],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t)

[[[ 1  2  4]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [88]:
t[:,0,1:] = 13#imp code
print(t)

[[[ 1 13 13]
  [ 4  5  6]]

 [[ 7 13 13]
  [10 11 12]]]


In [89]:
t[:,1,0:] = 2
print(t)

[[[ 1 13 13]
  [ 2  2  2]]

 [[ 7 13 13]
  [ 2  2  2]]]


In [90]:
#if we want to update the entire row


In [91]:
t = np.array([[[1,2,4],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t)

[[[ 1  2  4]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [92]:
t[:,1,:] = [[2,3,5],[11,22,33]] #imp code to note 
print(t)

[[[ 1  2  4]
  [ 2  3  5]]

 [[ 7  8  9]
  [11 22 33]]]


# initializing the different types of array


In [93]:
import numpy as np
np.zeros(7)


array([0., 0., 0., 0., 0., 0., 0.])

In [94]:
np.zeros((5,5)) #single dimensional array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [95]:
np.zeros((3,5,5)) #three dimensional array 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [96]:
np.zeros((2,3,5,5)) #here the the entire (5,5) is repeating for 3 times in 2 subcoloums

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [97]:
np.zeros((3,2,5,5) ,dtype="int32")

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]])

In [98]:
np.ones((3,4,2,2),dtype="float32")

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)

In [99]:
np.ones((3,3,3,3),dtype = "int32")


array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]]])

In [100]:
# in order to insert any other number than zero 0r 1 
#we can use the full function 

In [101]:
np.full((3,3),100,dtype= "float32")

array([[100., 100., 100.],
       [100., 100., 100.],
       [100., 100., 100.]], dtype=float32)

In [102]:
np.full((3,3),100,dtype= "int32")

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [103]:
np.arange(6,12).reshape(3,2)

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [104]:
np.random.randint(3,size= (3,2))

array([[1, 0],
       [1, 1],
       [2, 1]])

In [105]:
# we can import any other array form somewhere

In [106]:
q = np.array([[1,2,4],[4,5,6]])
print(q)

[[1 2 4]
 [4 5 6]]


In [107]:
np.full_like(a,4)

array([[4., 4., 4.],
       [4., 4., 4.]])

# to print the random value 

In [108]:
np.random.rand(4,5)

array([[0.98107197, 0.73146569, 0.52775382, 0.33751987, 0.20303911],
       [0.16245145, 0.3815955 , 0.07865554, 0.79658257, 0.54867744],
       [0.30209144, 0.70455479, 0.4068683 , 0.87855652, 0.53319038],
       [0.91724378, 0.32478816, 0.9106257 , 0.66018836, 0.99049975]])

In [109]:
#to import some of the random numbers

In [110]:
import numpy as np

In [111]:
np.random.randint(4,size=(3,3)) #here the value 4 means the array wil have the value till with mix of 4

array([[0, 2, 0],
       [2, 1, 2],
       [2, 2, 1]])

In [112]:
np.random.randint(7,size=(5,5,5)) #the numbers in the cells will be in the range from 0 to 7

array([[[4, 3, 0, 6, 5],
        [4, 2, 1, 0, 0],
        [6, 1, 5, 1, 5],
        [5, 1, 5, 4, 6],
        [4, 6, 4, 0, 1]],

       [[0, 0, 5, 1, 4],
        [1, 2, 1, 1, 1],
        [3, 4, 5, 3, 3],
        [1, 0, 3, 6, 0],
        [1, 0, 1, 0, 2]],

       [[1, 3, 1, 2, 2],
        [5, 3, 1, 4, 5],
        [5, 3, 2, 3, 5],
        [5, 2, 5, 4, 4],
        [5, 5, 3, 6, 0]],

       [[1, 2, 6, 5, 0],
        [3, 4, 2, 4, 2],
        [1, 4, 2, 4, 6],
        [2, 5, 1, 0, 1],
        [0, 1, 3, 0, 3]],

       [[6, 3, 1, 0, 5],
        [1, 5, 2, 2, 2],
        [0, 0, 5, 4, 2],
        [5, 5, 6, 1, 0],
        [4, 1, 5, 5, 6]]])

# to print the identity matrix



In [113]:
import numpy as np


In [114]:

arr=np.identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [115]:
arr =np. identity(6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [116]:
p = np.array([[1,2,3],[4,5,6]])
print(p)

[[1 2 3]
 [4 5 6]]


In [117]:
p = np.array([[[1,2,3],[7,8,9]],[[4,5,6],[10,11,12]]])
print(p)


[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


# explanation for this is in the bookmark tabs


In [118]:
j =np.repeat(p,3,axis = 1) 
print(j)

[[[ 1  2  3]
  [ 1  2  3]
  [ 1  2  3]
  [ 7  8  9]
  [ 7  8  9]
  [ 7  8  9]]

 [[ 4  5  6]
  [ 4  5  6]
  [ 4  5  6]
  [10 11 12]
  [10 11 12]
  [10 11 12]]]


In [119]:
q=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(q)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [120]:
m = np.repeat(q,3,axis = 0)
print(m)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]


In [121]:
m=np.repeat(q,3,axis = 1 )
print(m)

[[[ 1  2  3]
  [ 1  2  3]
  [ 1  2  3]
  [ 4  5  6]
  [ 4  5  6]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 7  8  9]
  [ 7  8  9]
  [10 11 12]
  [10 11 12]
  [10 11 12]]]


In [122]:
s = np.array([[6,7],[8,9]])
print(s)

[[6 7]
 [8 9]]


In [123]:
np.repeat(s,3,axis = 0)

array([[6, 7],
       [6, 7],
       [6, 7],
       [8, 9],
       [8, 9],
       [8, 9]])

In [124]:
np.repeat(s,3,axis=1)

array([[6, 6, 6, 7, 7, 7],
       [8, 8, 8, 9, 9, 9]])

In [125]:
np.repeat(q,3,axis = 0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [126]:
np.repeat(q,3,axis = 1)

array([[[ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 7,  8,  9],
        [ 7,  8,  9],
        [10, 11, 12],
        [10, 11, 12],
        [10, 11, 12]]])